[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "activity"
path = "src/activitylib.rs"

[dependencies]
chrono = "0.4.38"
thiserror = "1.0"
crossbeam = "0.8.4"
colored = "2.1.0"